### ISSUE TITLE
Cannot Copy Files

### ISSUE THREAD

**Issue by Meizikyn** [sagemathinc/cocalc-docker#20]
When attempting to copy anything via. CoCalc Interface, only receive error "failed" in red balloon.

console log shows the following: (src MLA.tex, dest /Courses)

```
2018-07-03T05:39:57.945Z - debug: execute_code: "rsync -rltgoDxH Templates/Latex/Writing/MLA.tex Courses"
2018-07-03T05:39:57.945Z - debug: Spawning the command rsync with given args -rltgoDxH,Templates/Latex/Writing/MLA.tex,Courses and timeout of 120s...
2018-07-03T05:39:57.960Z - debug: Listen for stdout, stderr and exit events.
2018-07-03T05:39:57.964Z - debug: BUG ****************************************************************************
2018-07-03T05:39:57.964Z - debug: Uncaught exception: ReferenceError: to_json is not defined
2018-07-03T05:39:57.965Z - debug: ReferenceError: to_json is not defined
    at ChildProcess.<anonymous> (/cocalc/src/smc-util-node/execute-code.coffee:176:17)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

2018-07-03T05:39:57.965Z - debug: BUG ****************************************************************************
[object Object]
    at process.<anonymous> (/cocalc/src/smc-project/local_hub.coffee:50:15)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.emit (/cocalc/src/smc-project/node_modules/source-map-support/source-map-support.js:454:21)
    at process._fatalException (bootstrap_node.js:378:26)

ReferenceError: to_json is not defined
    at ChildProcess.<anonymous> (/cocalc/src/smc-util-node/execute-code.coffee:176:17)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

error: Forever detected script exited with code: 1
error: Script restart attempt #4
```

Looks like it starts with missing `to_json` definition?

**Comment by williamstein** [comment]
Copy works fine now.
