### ISSUE TITLE
update to sage-9.0

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#65]
This definitely does **not** just work, even after https://github.com/sagemathinc/cocalc/issues/4212

Some issues after building with sage-9.0:

- smc-sage-server fails with this:
```

~$ smc-sage-server start
sage_server: starting...
sage_server: port=40663
sage_server: setting logfile to /projects/3b291300-23b1-4e26-90ba-4ab47e46676b/.smc/sage_server/sage_server.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/smc_sagews/sage_server.py", line 94, in <module>
    from . import sage_parsing, sage_salvus
  File "/usr/local/lib/python2.7/dist-packages/smc_sagews/sage_salvus.py", line 25, in <module>
    import sage.all
ModuleNotFoundError: No module named 'sage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/smc_sagews/sage_server_command_line.py", line 73, in main
    start()
  File "/usr/local/lib/python2.7/dist-packages/smc_sagews/sage_server_command_line.py", line 41, in start
    from . import sage_server
  File "/usr/local/lib/python2.7/dist-packages/smc_sagews/sage_server.py", line 96, in <module>
    import sage_parsing, sage_salvus
ModuleNotFoundError: No module named 'sage_parsing'
```

- The SageMath Jupyter kernel fails to start.

- The kernel list includes Python2 (SageMath), which isn't meaningful anymore.

**Comment by williamstein** [comment]
Note that I successfully did this for https://github.com/sagemathinc/cocalc-kubernetes, so copying whatever changes I made there should work to easily resolve this problem.

**Comment by williamstein** [comment]
Done!
