### ISSUE TITLE
support 3d graphics in sagetex

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc-docker#69]
This document is reported to not work in cocalc-docker, but does work on https://cocalc.com:  
```
\documentclass{article}
\usepackage{sagetex}
\begin{document}
\begin{sageblock}
var('x,y')
f1(x,y) = (x^2 - y^2)
zmin, zmax = -2,2
cm = colormaps.Spectral
def c(x,y): return float((f1(x,y)-zmin)/(zmax-zmin))
S1= plot3d(f1, (x,-1.5,1.5), (y,-1.5,1.5),color=(c,cm),
           frame = False)
\end{sageblock}

And the figure

\sageplot[scale =1, trim = {3cm, 4cm, 0cm, 5cm}, clip]{S1}
\end{document}
```

![image](https://user-images.githubusercontent.com/1276278/75745988-b8ff1f80-5ccd-11ea-8381-29295aa7fa18.png)

My first guess is something isn't installed (jmol?  tachyon?)...

**Comment by williamstein** [comment]
To reproduce this:

1. Create a sage worksheet
2. Type `sphere().save('a.png')`
3. See a stacktrace:
```
Error in lines 1-1
Traceback (most recent call last):
  File "/usr/local/sage/local/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1234, in execute
    flags=compile_flags), namespace, locals)
  File "", line 1, in <module>
  File "sage/plot/plot3d/base.pyx", line 1635, in sage.plot.plot3d.base.Graphics3d.save (build/cythonized/sage/plot/plot3d/base.c:21488)
    self.save_image(filename, **kwds)
  File "sage/plot/plot3d/base.pyx", line 1564, in sage.plot.plot3d.base.Graphics3d.save_image (build/cythonized/sage/plot/plot3d/base.c:21046)
    self._save_image_png(filename, **kwds)
  File "sage/plot/plot3d/base.pyx", line 1526, in sage.plot.plot3d.base.Graphics3d._save_image_png (build/cythonized/sage/plot/plot3d/base.c:20683)
    scene = self._rich_repr_jmol(**opts)
  File "sage/plot/plot3d/base.pyx", line 276, in sage.plot.plot3d.base.Graphics3d._rich_repr_jmol (build/cythonized/sage/plot/plot3d/base.c:7482)
    jdata.export_image(targetfile=preview_png, datafile=script,
  File "/usr/local/sage/local/lib/python2.7/site-packages/sage/interfaces/jmoldata.py", line 181, in export_image
    raise RuntimeError("Jmol failed to create file %s, see %s for details"%(repr(targetfile), repr(scratchout)))
RuntimeError: Jmol failed to create file '/projects/a56a88e7-9b4b-4805-a167-f2c078ee66d1/.sage/temp/fa32859543a9/60318/dir_LzbiKY/preview.png', see '/projects/a56a88e7-9b4b-4805-a167-f2c078ee66d1/.sage/temp/fa32859543a9/60318/tmp_pF1UH9.txt' for details
```

 Same ending:

![image](https://user-images.githubusercontent.com/1276278/75922286-90833c80-5e17-11ea-9e1a-facf4cef987b.png)

Exactly the same thing works fine on https://cocalc.com with sage-8.9.  It is [broken (in a different way!) with sage-9.0 though](https://github.com/sagemathinc/cocalc/issues/4432).

**Comment by Alessandro-Barbieri** [comment]
> Note that "jmol" isn't an optional sage package. Maybe we need some sort of Java packages to be installed, but I don't know.
start with installing `default-jre`
https://packages.debian.org/sid/jmol

**Comment by williamstein** [comment]
Hi tried install default-jre **as root** and it is already installed:
```
root@fa32859543a9:/# apt install default-jre
Reading package lists... Done
Building dependency tree       
Reading state information... Done
default-jre is already the newest version (2:1.11-68ubuntu1~18.04.1).
default-jre set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 89 not upgraded.
```

I then tried the above test, but was **lazy** and did so as root... and surprisingly, jmol worked!
```
root@fa32859543a9:/# umask 022
root@fa32859543a9:/# sage
Forcing sage-location, probably because a new package was installed.
Cleaning up, do not interrupt this.
Done cleaning.
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.9, Release Date: 2019-09-29                     │
│ Using Python 2.7.15. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: sphere().save('a.png')
sage:                                                                                                                                                                                       
Exiting Sage (CPU time 0m0.34s, Wall time 0m8.27s).
root@fa32859543a9:/# ls -l a.png
-rw-r--r-- 1 root root 40419 Mar  5 01:19 a.pngs
```
I then tried `su - <a normal user>` and the test failed.

Surprise conclusion: this can't be a "something is not installed" problem, and is instead probably a permissions issue.

**Comment by williamstein** [comment]
That txt file with the reason why things aren't working is deleted only after the sage process exists.  So here is what it says:
```
RuntimeError: Jmol failed to create file '/projects/a56a88e7-9b4b-4805-a167-f2c078ee66d1/.sage/temp/fa32859543a9/65292/dir_GQcgIB/preview.png', see '/projects/a56a88e7-9b4b-4805-a167-f2c078ee66d1/.sage/temp/fa32859543a9/65292/tmp_QkfeFh.txt' for details

[1]+  Stopped                 sage
~$ more /projects/a56a88e7-9b4b-4805-a167-f2c078ee66d1/.sage/temp/fa32859543a9/65292/tmp_QkfeFh.txt
Error: Unable to access jarfile /usr/local/sage/local/share/jmol/JmolData.jar
```

**Comment by williamstein** [comment]
And the permissions are indeed wrong for exactly one directory:
```
root@fa32859543a9:/# ls -lhtd /usr/local/sage/local/share/jmol
drwx------ 4 sage sage 4.0K Jan 16 22:01 /usr/local/sage/local/share/jmol
```

This might be a bug in Sage (perhaps in the jmol standard package), that could impact other system-wide install of Sage by default.  

Fixing permissions via `chmod a+rx /usr/local/sage/local/share/jmol`, and then it totally works:

![2020-03-04 17_32_30-Untitled - CoCalc](https://user-images.githubusercontent.com/1276278/75939174-537e7080-5e3e-11ea-955d-8d733fe0ea2a.png)

For now, I'm going to just add that chmod line to the Dockerfile, rebuild our docker image, and not worry about this further.  Maybe some good Samaritan will try a clean sage build and check if this happens there, and if so report it to https://trac.sagemath.org/.  I'm too busy...
